// Generated by CoffeeScript 1.6.3
(function() {
  var Fldoc;

  Fldoc = (function() {
    function Fldoc(build) {
      this.build = build;
    }

    return Fldoc;

  })();

}).call(this);

/*
//@ sourceMappingURL=fldoc.map
*/
